# Generated by Django 2.0.1 on 2019-10-31 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(16)], verbose_name='Card Number')),
                ('password', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Password')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Balance')),
                ('full_name', models.CharField(max_length=40, unique=True, verbose_name='Full name')),
                ('cvv', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Cvv')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
    ]
