# Generated by Django 2.0.1 on 2019-10-31 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankomat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='card_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(16)], verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cvv',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(3)], verbose_name='Cvv'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='password',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(4)], verbose_name='Password'),
        ),
    ]
