# Generated by Django 2.0.1 on 2019-10-31 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankomat', '0003_auto_20191031_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Card Number'),
        ),
    ]
