# Generated by Django 2.0.1 on 2019-10-31 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankomat', '0004_auto_20191031_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='card_number',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_number',
            field=models.CharField(default=1234123412341234, max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Cart Number'),
            preserve_default=False,
        ),
    ]
